Tcollector init script to control tcollector

diff --git a/tcollector b/tcollector
--- a/tcollector
+++ b/tcollector
@@ -5,10 +5,16 @@
 # Required-Stop:     $local_fs $network $named $time $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Description:       opsmxagent
+# Description:       opsmx tcollector
 ###  END INIT INFO
 
 #Follow standards https://wiki.debian.org/LSBInitScripts
+
+red=$(tput setaf 1)
+green=$(tput setaf 2)
+normal=$(tput sgr0)
+blink=$(tput blink)
+yellow=$(tput setaf 3)
 
 SCRIPT="python /opt/tcollector/tcollector.py"
 NAME="tcollector"
@@ -18,11 +24,15 @@ LOGFILE="/var/log/$NAME.log"
 start() {
   if [ -f "$PIDFILE" ] && (ps -p $(cat "$PIDFILE") > /dev/null 2>&1);
   then
-     echo 'tcollector already running' >&2
+     echo ${yellow}'Tcollector(OpsMx) already running'${normal} >&2
      return 1
   fi
   sudo sh -c "$SCRIPT"
-  echo 'tcollector started' >&2
+  if [ $? != "0" ];then
+    echo ${red}'Tcollector(OpsMx) is not started'${normal} >&2
+	exit 1
+  fi
+  echo ${green}'Tcollector(OpsMx) started'${normal} >&2
 }
 
 stop() {
@@ -30,10 +40,9 @@ stop() {
   then
     kill -0 $(cat "$PIDFILE") 2> /dev/null
     sudo kill -15 $(cat "$PIDFILE") && sudo rm -f "$PIDFILE"
-    #echo "" > /var/run/tcollector.pid
-    echo 'tcollector stopped' >&2
+    echo ${red}'Tcollector(OpsMx) stopped'${normal} >&2
   else
-    echo 'tcollector not running' >&2
+    echo ${red}'Tcollector(OpsMx) is not running'${normal} >&2
     return 1
   fi
 }
@@ -41,14 +50,14 @@ stop() {
 status() {
   if [ -f "$PIDFILE" ] && (ps -p $(cat "$PIDFILE") > /dev/null 2>&1);
   then
-    echo "tcollector is running" >&2
+    echo ${green}'Tcollector(OpsMx) is running'${normal} >&2
   else
-    echo 'tcollector is not running' >&2
+    echo ${red}'Tcollector(OpsMx) is not running'${normal} >&2
   fi
 }
 
 uninstall() {
-  echo -n "Are you really sure you want to uninstall this service? That cannot be undone. [yes|No] "
+  echo -n "Are you really sure you want to uninstall this OpsMx tcollector? That cannot be undone. [yes|No] "
   local SURE
   read SURE
   if [ "$SURE" = "yes" ]; then
